controller_list:
  - name: fake_slam_dunk_controller
    type: $(arg execution_type)
    joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
initial: # Define initial robot poses.
  - group: slam_dunk
    pose: idle
